### ISSUE TITLE
How does this work

### ISSUE THREAD

**Issue by nmcc1212** [FewHakko/HoneyGain-Bot#1]
Please could you explain what this does and how it works

**Comment by ochen1** [comment]
Yeah. It would be very much appreciated.

**Comment by ochen1** [comment]
You can find a hint of an explanation of what this is here: https://translate.google.ca/translate?hl=en&sl=ru&u=https://miped.ru/f/threads/xaljava-honeygain-stavim-na-dedik-i-poluchaem-bot-2020.101911/
